spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics_db
    username: postgres
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # O Hibernate criará a tabela para você na inicialização
    show-sql: true

# Configuração da nossa API Externa (Wiremock)
logistics:
  viacep:
    url: http://localhost:8080