server:
  port: 8081

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      sqs:
        endpoint: http://localhost:4566
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics_db
    username: postgres
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logistics:
  viacep:
    url: http://localhost:8080